"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from dotenv import load_dotenv
load_dotenv()
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'insecure-dev-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.railway.app', 'testserver', 'officetim.com', 'www.officetim.com']

# Django 4.0+ requires exact origins with scheme; wildcards are not supported.
# You can override via env var, e.g. CSRF_TRUSTED_ORIGINS="https://your-app.up.railway.app,https://example.com"
_csrf_from_env = os.getenv('CSRF_TRUSTED_ORIGINS')
if _csrf_from_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_from_env.split(',') if o.strip()]
else:
    # Default to the current Railway domain; adjust if your deploy URL changes
    CSRF_TRUSTED_ORIGINS = [
        'https://unused-twig-production.up.railway.app',
        'https://officetim.com',
        'https://www.officetim.com',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    # Image uploads
    'django_cleanup.apps.CleanupConfig',
    'posts',
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
   'corsheaders.middleware.CorsMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# django_project/settings.py




_db_url = os.getenv('DATABASE_URL')
try:
    default_db = dj_database_url.parse(_db_url, conn_max_age=600) if _db_url else None
except Exception:
    default_db = None

if not default_db:
    default_db = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }

# In production, require a real DATABASE_URL to avoid resetting data on deploys
if not DEBUG:
    if not _db_url:
        raise ImproperlyConfigured(
            "DATABASE_URL is required in production. Set it in Railway service variables to your persistent Postgres URL."
        )
    # Guard against placeholder values sometimes left accidentally
    if any(token in _db_url for token in ["your-host", "PORT", "dbname"]):
        raise ImproperlyConfigured(
            "DATABASE_URL appears to be a placeholder. Please set the exact Postgres connection string from Railway."
        )

DATABASES = {
    'default': default_db
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use manifest storage in production when static files are collected.
# To temporarily avoid admin 500 errors before collectstatic, set USE_MANIFEST_STATIC=0 in env.
_use_manifest = os.getenv('USE_MANIFEST_STATIC', '1') == '1'
STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if _use_manifest else
    'whitenoise.storage.CompressedStaticFilesStorage'
)

# Media (user uploads)
# Defaults to local disk, but can be overridden via env for persistent volumes
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
_media_root_env = os.getenv('MEDIA_ROOT')
MEDIA_ROOT = Path(_media_root_env) if _media_root_env else (BASE_DIR / 'media')

# Allow serving media files via Django in non-DEBUG when explicitly enabled
SERVE_MEDIA = os.getenv('SERVE_MEDIA', '1') == '1'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-cors-headers
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# Trust proxy headers so Django knows the original host/scheme (for correct https URLs)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Secure cookies in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Optional remote media storage backends
STORAGE_BACKEND = os.getenv('STORAGE_BACKEND', 'local').lower()
if STORAGE_BACKEND == 's3':
    INSTALLED_APPS.append('storages')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')  # optional for non-AWS providers
    AWS_S3_SIGNATURE_VERSION = os.getenv('AWS_S3_SIGNATURE_VERSION', 's3v4')
    AWS_S3_ADDRESSING_STYLE = os.getenv('AWS_S3_ADDRESSING_STYLE', 'virtual')
    AWS_QUERYSTRING_AUTH = os.getenv('AWS_QUERYSTRING_AUTH', '0') == '1'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': os.getenv('AWS_S3_CACHE_CONTROL', 'max-age=86400'),
    }
    _aws_custom_domain = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    if _aws_custom_domain:
        MEDIA_URL = f"https://{_aws_custom_domain}/"
    elif AWS_STORAGE_BUCKET_NAME and AWS_S3_REGION_NAME:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"
elif STORAGE_BACKEND == 'cloudinary':
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # When CLOUDINARY_URL is set, django-cloudinary-storage will generate URLs.

# Email settings
# If EMAIL_HOST is provided, use SMTP; otherwise console backend (prints emails to logs)
if os.getenv('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', '1') == '1'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', '0') == '1'  # prefer TLS (587). Use SSL with port 465.
    EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
CONTACT_FORWARD_TO = os.getenv('CONTACT_FORWARD_TO', 'timtvogt@gmail.com')

